export const GET_CHOCOLATE_DATA = "GET_CHOCOLATE";
export const GET_CHOCOLATE_DATA_SUCCESS = "GET_CHOCOLATE_DATA_SUCCESS";
export const GET_CHOCOLATE_DATA_FAILURE = "GET_CHOCOLATE_DATA_FAILURE";

export const GET_CANDY_DATA = "GET_CANDY_DATA";
export const GET_CANDY_DATA_SUCCESS = "GET_CANDY_DATA_SUCCESS";
export const GET_CANDY_DATA_FAILURE = "GET_CANDY_DATA_FAILURE";

export const GET_TOFFEE_DATA = "GET_TOFFE_DATA";
export const GET_TOFFEE_DATA_SUCCESS = "GET_TOFFEE_DATA_SUCCESS";
export const GET_TOFFEE_DATA_FAILURE = "GET_TOFFEE_DATA_FAILURE";
